config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :votes, only: [:create]
  resources :states, only: [:show, :index]
  resources :concerns do
  	resources :comments
  end
  resources :users, only: [:show, :destroy]
  resources :sessions
  get '/state/concerns', to: 'states#show'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/searches', to: 'searches#index'
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :concerns
  has_many :legislators
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  def index
    @states = State.all
  end

  def show
    @state = State.find(state_id)
    @first_senator = Legislator.where(state_id: @state.id).first
    @second_senator = Legislator.where(state_id: @state.id).last


    # @senator1_first_name = first_senator.senator1_first_name
    # @senator1_last_name = first_senator.senator1_last_name
    # @senator1_phone = first_senator.senator1_phone
    # @senator1_email = first_senator.senator1_oc_email
    # @senator1_facebook = first_senator.senator1_facebook_id
    # @senator1_twitter = first_senator.senator1_twitter_id
    # @senator1_website = first_senator.senator1_website
    # @senator1_contact = first_senator.senator1_contact_form
    # @senator1_votesmart = first_senator.senator1_votesmart_id
    # @senator1_youtube = first_senator.senator1_youtube_id
    # @senator1_party = first_senator.senator1_party
    # @senator1_office = first_senator.senator1_office

    # @senator2_first_name = second_senator.senator2_first_name
    # @senator2_last_name = second_senator.senator2_last_name
    # @senator2_phone = second_senator.senator2_phone
    # @senator2_email = second_senator.senator2_oc_email
    # @senator2_facebook = second_senator.senator2_facebook_id
    # @senator2_twitter = second_senator.senator2_twitter_id
    # @senator2_website = second_senator.senator2_website
    # @senator2_contact = second_senator.senator2_contact_form
    # @senator2_votesmart = second_senator.senator2_votesmart_id
    # @senator2_youtube = second_senator.senator2_youtube_id
    # @senator2_party = second_senator.senator2_party
    # @senator2_office = second_senator.senator2_office

    @article_results = HTTParty.get("http://api.nytimes.com/svc/search/v2/articlesearch.json?q=#{URI.encode(@state.name)}+state&sort=newest&api-key=89e284f8eda6570a89f89d232d8aa6d6%3A0%3A71812658")
    # @article1 = Article.new(@state.name)
    @articles = []
    @article_results["response"]["docs"][0..4].each do |article|
      @articles << Article.new(@state.name, article["headline"]["main"], article["web_url"], article["snippet"], article["abstract"], article["pub_date"])
    end
  end

  private
    def state_id
      params[:state] ? params[:state][:state_id] : params[:format]
    end
end

app/helpers/state_helper.rb
module StateHelper

  
end

app/views/states/index.html.erb
<br>
<% @states.each do |state| %>
  <%= link_to state.name, state_path(state) %><br>
<% end %>

app/views/states/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="text-center">
      <h1><%= @state.name %></h1>
    </div>
  <% unless @state.concerns.empty? %>
    <table class="table">
      <thead>
        <tr class ="danger">
          <td>Concerns that affect this state</td>
          <td>Agree</td>
          <td>Disagree</td>
        </tr>
      </thead>
      <tbody>
        <% @state.concerns.each do |concern| %>
          <tr class = "warning">
            <td><%= link_to concern.title, concern_path(concern) %></td>
            <td><%= concern.upvotes %></td>
            <td><%= concern.downvotes %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br><br><br><br><br>
  <% end %>

  <!---------NYTIMES ARTICLES--------->

  <img src="http://www.nytimes-se.com/nytse/wp-content/themes/nytimes/media/nytlogo379x64.gif" alt="NewYorkTimesLogo" class="img-responsive block">
    <br>
    <% @articles.each do |article| %>
    <ul>
      <li><h4><u><%= link_to article.headline, article.web_url %></u></h4></li>
      <h6><%= article.pub_date.gsub(/T.+/, "")%> </h6>
      <h5>"<%= article.snippet %>"</h5>
      </ul>
    <% end %>
</div>


  <!--------- SENATORS -------->
  <div class = "col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3><%= @state.name %> Senators: </h3>
        <h2><%= @first_senator.first_name %> <%= @first_senator.last_name %> (<%=@first_senator.party%>)</h2>
        Phone: <%= @first_senator.phone %><br>
        Email: <%= @first_senator.oc_email %><br>
        Office: <%= @first_senator.office %><br><br>
        Find Senator <%= @first_senator.last_name %> online:
        <% if !@first_senator.website.nil? %>
        <%= link_to "Website", @first_senator.website %>
        <% end %>
        <% if !@first_senator.facebook_id.nil? %>
        <%= link_to "Facebook", "http://www.facebook.com/#{@first_senator.facebook_id}" %>
        <% end %>
        <% if !@first_senator.twitter_id.nil? %>
        <%= link_to "Twitter", "http://www.twitter.com/#{@first_senator.twitter_id}" %>
        <% end %>
        <% if !@first_senator.youtube_id.nil? %>
        <%= link_to "Youtube", "http://www.youtube.com/#{@first_senator.youtube_id}" %>
        <% end %>
        <% if !@first_senator.votesmart_id.nil? %>
        <%= link_to "Votesmart", "http://votesmart.org/candidate/biography/#{@first_senator.votesmart_id}" %>
        <% end %><br>
        <% if !@first_senator.contact_form.nil? %>
        <%= link_to "Contact", @first_senator.contact_form %>
        <% end %>

      </div>
    </div>

    <div class="thumbnail">
      <div class="caption">
        <h2><%= @second_senator.first_name %> <%= @second_senator.last_name %> (<%=@second_senator.party%>)</h2><br>
        Phone: <%= @second_senator.phone %><br>
        Email: <%= @second_senator.oc_email %><br>
        Office: <%= @second_senator.office %><br><br>
        Find Senator <%= @second_senator.last_name %> online:
        <% if !@second_senator.website.nil? %>
        <%= link_to "Website", @second_senator.website %>
        <% end %>
        <% if !@second_senator.facebook_id.nil? %>
        <%= link_to "Facebook", "http://www.facebook.com/#{@second_senator.facebook_id}" %>
        <% end %>
        <% if !@second_senator.twitter_id.nil? %>
        <%= link_to "Twitter", "http://www.twitter.senator2_com/#{@second_senator.twitter_id}" %>
        <% end %>
        <% if !@second_senator.youtube_id.nil? %>
        <%= link_to "Youtube", "http://www.youtube.com/#{@second_senator.youtube_id}" %>
        <% end %>
        <% if !@second_senator.votesmart_id.nil? %>
        <%= link_to "Votesmart", "http://votesmart.org/candidate/biography/#{@second_senator.votesmart_id}" %>
        <% end %><br>
        <% if !@second_senator.contact_form.nil? %>
        <%= link_to "Contact", @second_senator.contact_form %>
        <% end %>

      </div>
    </div>



</div>