config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :votes, only: [:create]
  resources :states, only: [:show, :index]
  resources :concerns do
  	resources :comments
  end
  resources :users, only: [:show, :destroy]
  resources :sessions
  get '/state/concerns', to: 'states#show'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/searches', to: 'searches#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  helper_method :sort_column, :sort_direction
  def index
    @concerns = Concern.order(sort_column + " " + sort_direction).paginate(
                                             page: params[:page], per_page: 10)
  end

  private
    def sort_column
      params[:sort] || 'title'
    end

    def sort_direction
      params[:direction] || 'asc'
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class = "jumbotron">
  <h1 id = "welcome">Welcome to FixIt</h1><br><br>  
  <%= form_tag("/state/concerns", method: "get") do %>
    <%= collection_select(:state, :state_id, State.all, :id, :name) %>
    <%= submit_tag "Find concerns by state", class: "btn btn-primary" %>
  <% end %>
</div>
<br><br>
<div class="concerns">
  <% if logged_in? %>
    <%= link_to "Post a New Concern", new_concern_path, class: "btn btn-primary" %><br>
  <% else %>
    <%= "Please log in to create a new concern" %>
  <% end %>
</div>
<br>
<div class ="search-concerns">
  <%= form_tag searches_path, :method => 'get' do %>
    <%= text_field_tag (:keyword) %>
    <%= submit_tag 'search for a concern', class: "btn btn-primary" %>
  <% end %>
</div>
<h3>All Concerns</h3>
<table class = "table table-striped">
  <thead>
    <tr class = "info">
      <td><%= sortable "title" %></td>
      <td><%= sortable "upvotes"  %></td>
      <td><%= sortable "downvotes" %></td>
      <td><%= sortable "result"   %></td>
      <td><%= sortable "total"    %></td>

    </tr>
  </thead>
  <tbody>
    <% @concerns.each do |c| %>
      <tr class = "warning">
        <td><%= link_to c.title, concern_path(c)%></td>
        <td><%= c.upvotes %></td>
        <td><%= c.downvotes %></td>
        <td><%= c.result %></td>
        <td><%= c.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="page_info">
  <%= page_entries_info @concerns %>
</div>
<%= will_paginate @concerns, :container => false %>