config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :votes, only: [:create]
  resources :states, only: [:show, :index]
  resources :concerns do
  	resources :comments
  end
  resources :users, only: [:show, :destroy]
  resources :sessions
  get '/state/concerns', to: 'states#show'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/searches', to: 'searches#index'
end

app/models/concern.rb
class Concern < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  belongs_to :state
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user
  has_many :comments, dependent: :destroy
end

app/models/concerns/legislator.rb
class Legislator
  belongs_to :state
  # attr_reader :state_name

  # def initialize(state_name)
  #   @state_name = state_name
  #   get_results
  # end

  # def get_results
  #   @results ||= HTTParty.get("http://congress.api.sunlightfoundation.com/legislators?title=Sen&state_name=#{URI.encode(state_name)}&apikey=019ce60aedb142ce9962d349c3b51e60")
  # # end

  # def state_name
  #   State.find(self.state_id).name 
  # end
  ###### Senator 1 ######

  # senator_attributes = ["first_name", "last_name", "phone", "oc_email", "facebook_id", "twitter_id", "website", "contact_form", "votesmart_id", "youtube_id", "party", "office"]

  # senator_attributes.each do |attribute|
  #   define_method "senator1_#{attribute}" do
  #     @results["results"].first[attribute]
  #   end

  #   define_method "senator2_#{attribute}" do
  #     @results["results"].last[attribute]
  #   end
  # end

  # def senator1_first_name
  #   @results["results"].first["first_name"]
  # end

  # def senator1_last_name
  #   @results["results"].first["last_name"]
  # end

  # def senator1_phone
  #   @results["results"].first["phone"]
  # end

  # def senator1_email
  #   @results["results"].first["oc_email"]
  # end

  # def senator1_facebook
  #   @results["results"].first["facebook_id"]
  # end

  # def senator1_twitter
  #   @results["results"].first["twitter_id"]
  # end

  # def senator1_website
  #   @results["results"].first["website"]
  # end

  # def senator1_contact
  #   @results["results"].first["contact_form"]
  # end

  # def senator1_votesmart
  #   @results["results"].first["votesmart_id"]
  # end

  # def senator1_youtube
  #   @results["results"].first["youtube_id"]
  # end

  # def senator1_party
  #   @results["results"].first["party"]
  # end

  # def senator1_office
  #   @results["results"].first["office"]
  # end


  # ###### Senator 2 ######

  # def senator2_first_name
  #   @results["results"].last["first_name"]
  # end

  # def senator2_last_name
  #   @results["results"].last["last_name"]
  # end

  # def senator2_phone
  #   @results["results"].last["phone"]
  # end

  # def senator2_email
  #   @results["results"].last["oc_email"]
  # end

  # def senator2_facebook
  #   @results["results"].last["facebook_id"]
  # end

  # def senator2_twitter
  #   @results["results"].last["twitter_id"]
  # end

  # def senator2_website
  #   @results["results"].last["website"]
  # end

  # def senator2_contact
  #   @results["results"].last["contact_form"]
  # end

  # def senator2_votesmart
  #   @results["results"].last["votesmart_id"]
  # end

  # def senator2_youtube
  #   @results["results"].last["youtube_id"]
  # end

  # def senator2_party
  #   @results["results"].last["party"]
  # end

  # def senator2_office
  #   @results["results"].last["office"]
  # end
end

app/controllers/concerns_controller.rb
class ConcernsController < ApplicationController
  before_action :set_concern, only: [:show, :edit, :update, :destroy]

  # GET /concerns
  # GET /concerns.json
  def index
    @concerns = Concern.order(params[:sort])
  end

  # GET /concerns/1
  # GET /concerns/1.json
  def show
  end

  # GET /concerns/new
  def new
    @concern = Concern.new
  end

  # GET /concerns/1/edit
  def edit
  end

  # POST /concerns
  # POST /concerns.json
  def create
    @concern = Concern.new(concern_params)
    respond_to do |format|
      if @concern.save
        format.html { redirect_to @concern, notice: 'Concern was successfully created.' }
        format.json { render :show, status: :created, location: @concern }
      else
        format.html { render :new }
        format.json { render json: @concern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerns/1
  # PATCH/PUT /concerns/1.json
  def update
    respond_to do |format|
      if @concern.update(concern_params)
        format.html { redirect_to @concern, notice: 'Concern was successfully updated.' }
        format.json { render :show, status: :ok, location: @concern }
      else
        format.html { render :edit }
        format.json { render json: @concern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerns/1
  # DELETE /concerns/1.json
  def destroy
    @concern.destroy
    respond_to do |format|
      format.html { redirect_to concerns_url, notice: 'Concern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_concern
    @concern = Concern.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def concern_params
    params.require(:concern).permit(:title, :description, :state_id, :creator_id)
  end
end

app/helpers/concerns_helper.rb
module ConcernsHelper
end

app/views/concerns/_form.html.erb
<%= form_for(@concern) do |f| %>
  <% if @concern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concern.errors.count, "error") %> prohibited this concern from being saved:</h2>
      <ul>
      <% @concern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"%><br>
  </div>
  <div class = "form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control"%><br>
  </div>
    <%= f.label :state_id %><br>
    <%= f.collection_select(:state_id, State.all, :id, :name, {:prompt=>true}, {:class=>'form-control'})%>
    <%= f.hidden_field :creator_id, :value => current_user.id %>

  <div class="actions">
    <br><%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/concerns/edit.html.erb
<h1>Editing Concern</h1>

<%= render 'form' %>

<%= link_to 'Show', @concern %> |
<%= link_to 'Back', concerns_path %>

app/views/concerns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concerns</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerns.each do |concern| %>
      <tr>
        <td><%= link_to concern.title, concern %></td>
        <% if logged_in? %>
        <td><%= link_to 'Edit', edit_concern_path(concern) %></td>
        <td><%= link_to 'Destroy', concern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
  <%= link_to 'New Concern', new_concern_path %><br>
<% else %>
  <%= "Please Log In to Create a New Concern" %> <br>
  <%= link_to 'login', login_path %>
<% end %> <br>

<%= link_to "Back", root_path %>

app/views/concerns/new.html.erb
<h1>New Concern</h1>

<%= render 'form' %>

<%= link_to 'Back', concerns_path %>

app/views/concerns/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h2>State: <%= link_to @concern.state.name, state_concerns_path(@concern.state) %></h2>
  <h3>Concern: <%= @concern.title %></h3>
  <p>Posted by: <%= link_to @concern.creator.name, user_path(@concern.creator)%> at <%= @concern.created_at.strftime("%B %d, %Y %r") %></p>

<div class="text-center">
    <p><h4>Description:</h4></p>
    <p><%= @concern.description %></p>
</div>
  <p><%= @concern.upvotes %> people agree!</p>
  <p><%= @concern.downvotes %> people disagree!</p>
</div>

<% if user_can_vote?(@concern) %>
  <%= form_for @concern.votes.new do |f| %>
    <%= f.hidden_field :voter_id, :value => current_user.id %>
    <%= f.hidden_field :concern_id, :value => @concern.id %>
    <%= f.hidden_field :upvote, :value => true %>
    <div class="col-lg-2 box">
      <button type="submit" class="center-block btn btn-success btn-lg">Agree</button>
    </div>
  <% end %>

  <%= form_for @concern.votes.new do |f| %>
   <%= f.hidden_field :voter_id, :value => current_user.id %>
    <%= f.hidden_field :concern_id, :value => @concern.id %>
    <%= f.hidden_field :upvote, :value => false %>
    <div class="col-lg-1 box">
      <button type="submit" class="center-block btn btn-danger btn-lg">Disagree</button>
    </div>
  <% end %>
<% end %>
<br><br><br><br>
<% unless @concern.comments.empty? %>
  <h4>Previous Comments:</h4>
  <ul>
    <% @concern.comments.each do |comment| %>
      <li><%= comment.content %></li>
      <%= comment.user.name %>
      <%= comment.created_at %><br>
    <% end %>
  </ul>
<% end %>

<div class = "form-group">
<% if logged_in? %>
  <h4>New Comment</h4>
  <%= form_tag("/concerns/#{@concern.id}/comments") do %>
    <%= hidden_field_tag('comment[user_id]', value = @current_user.id) %>
    <%= text_area_tag('comment[content]') %><br>
    <%= submit_tag "Create Comment", class: "btn btn-primary" %>
  <% end %>
  <% else %>
    <p><%= "Please "%><%= link_to 'Login', login_path%><%= " to Post a Comment" %></p>
  <% end %>
</div>

<%= link_to 'Back', concerns_path %>